/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplicationprojetoteste;

/**
 *
 * @author Info2410
 */
public class JFrameSobre extends javax.swing.JFrame {

    /**
     * Creates new form JFrameSobre
     */
    public JFrameSobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelbusiness = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabeldevelopers = new javax.swing.JLabel();
        jLabelbusiness1 = new javax.swing.JLabel();
        jLabelversion = new javax.swing.JLabel();
        jButtonfechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabelbusiness.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelbusiness.setIcon(new javax.swing.ImageIcon("C:\\Users\\info2410\\Documents\\NetBeansProjects\\Icons\\icons8-companhia-50.png")); // NOI18N
        jLabelbusiness.setText("Empresa: SYSFREQ AND BENEFIT");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelTitulo.setText("Sobre nós");

        jLabeldevelopers.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabeldevelopers.setIcon(new javax.swing.ImageIcon("C:\\Users\\info2410\\Documents\\NetBeansProjects\\Icons\\team(1).png")); // NOI18N
        jLabeldevelopers.setText("Desenvolvedores: Heitor Baldoni, Matheus Emanuel, Pedro Inácio, Gustavo Batista e Eduardo Souto.\n");

        jLabelbusiness1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelbusiness1.setIcon(new javax.swing.ImageIcon("C:\\Users\\info2410\\Documents\\NetBeansProjects\\Icons\\icons8-companhia-50.png")); // NOI18N
        jLabelbusiness1.setText("Empresa: SYSFREQ AND BENEFIT");

        jLabelversion.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelversion.setIcon(new javax.swing.ImageIcon("C:\\Users\\info2410\\Documents\\NetBeansProjects\\Icons\\icons8-versão-64.png")); // NOI18N
        jLabelversion.setText("Versão: 1.0");

        jButtonfechar.setBackground(new java.awt.Color(153, 153, 255));
        jButtonfechar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButtonfechar.setForeground(new java.awt.Color(0, 0, 153));
        jButtonfechar.setText("Fechar");
        jButtonfechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfecharActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Ano: 2025");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabelTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabeldevelopers))
                    .addComponent(jLabelbusiness1)
                    .addComponent(jLabelversion)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(jButtonfechar)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeldevelopers)
                .addGap(26, 26, 26)
                .addComponent(jLabelbusiness1)
                .addGap(41, 41, 41)
                .addComponent(jLabelversion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jButtonfechar)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonfecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfecharActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonfecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameSobre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonfechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelbusiness;
    private javax.swing.JLabel jLabelbusiness1;
    private javax.swing.JLabel jLabeldevelopers;
    private javax.swing.JLabel jLabelversion;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
