/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplicationprojetoteste;

/**
 *
 * @author Info2410
 */
public class JFrameLogin extends javax.swing.JFrame {

    /**
     * Creates new form JFrameLogin
     */
    public JFrameLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupfuncao = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelnome = new javax.swing.JLabel();
        jTextFieldnome = new javax.swing.JTextField();
        jPasswordFieldsenha = new javax.swing.JPasswordField();
        jLabelsenha = new javax.swing.JLabel();
        jButtonEntrar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabelResposta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonfuncio = new javax.swing.JButton();
        jButtonProf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonaluno = new javax.swing.JRadioButton();
        jRadioButtonProf = new javax.swing.JRadioButton();
        jRadioButtonfuncbenefi = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabelnome.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelnome.setText("Nome do usuário:");

        jTextFieldnome.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        jPasswordFieldsenha.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        jLabelsenha.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelsenha.setText("Senha:");

        jButtonEntrar.setBackground(new java.awt.Color(204, 255, 204));
        jButtonEntrar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButtonEntrar.setForeground(new java.awt.Color(0, 0, 153));
        jButtonEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplicationprojetoteste/entrar.png"))); // NOI18N
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });

        jButtonLimpar.setBackground(new java.awt.Color(204, 255, 204));
        jButtonLimpar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButtonLimpar.setForeground(new java.awt.Color(0, 0, 153));
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplicationprojetoteste/limpar.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jLabelResposta.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Não possui uma conta? Cadastre-se agora!!");

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Aluno");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonfuncio.setBackground(new java.awt.Color(204, 255, 204));
        jButtonfuncio.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButtonfuncio.setForeground(new java.awt.Color(0, 0, 153));
        jButtonfuncio.setText("Funcionário");
        jButtonfuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfuncioActionPerformed(evt);
            }
        });

        jButtonProf.setBackground(new java.awt.Color(204, 255, 204));
        jButtonProf.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButtonProf.setForeground(new java.awt.Color(0, 0, 153));
        jButtonProf.setText("Professor");
        jButtonProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProfActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Login");

        buttonGroupfuncao.add(jRadioButtonaluno);
        jRadioButtonaluno.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jRadioButtonaluno.setText("Aluno");

        buttonGroupfuncao.add(jRadioButtonProf);
        jRadioButtonProf.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jRadioButtonProf.setText("Professor");

        buttonGroupfuncao.add(jRadioButtonfuncbenefi);
        jRadioButtonfuncbenefi.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jRadioButtonfuncbenefi.setText("Funcionário do benefício");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Tipo de usuário:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonaluno)
                    .addComponent(jButtonEntrar))
                .addGap(62, 62, 62)
                .addComponent(jButtonLimpar)
                .addGap(418, 418, 418))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jButton1)
                        .addGap(147, 147, 147)
                        .addComponent(jLabelResposta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonfuncio)
                        .addGap(56, 56, 56)
                        .addComponent(jButtonProf))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2)
                        .addGap(129, 129, 129)
                        .addComponent(jRadioButtonfuncbenefi)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonProf))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(jLabelsenha))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabelnome)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordFieldsenha, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                            .addComponent(jTextFieldnome)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jLabel1)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelnome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelsenha)
                    .addComponent(jPasswordFieldsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButtonaluno)
                    .addComponent(jRadioButtonfuncbenefi)
                    .addComponent(jRadioButtonProf))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEntrar))
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabelResposta)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButtonfuncio)
                            .addComponent(jButtonProf))
                        .addGap(121, 121, 121))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        //Esse código é somente temporário para testar a funcionalidade da tela de login
String tipo;
        String nome = jTextFieldnome.getText();
        String senha = jPasswordFieldsenha.getText();
tipo = null;
 if (jRadioButtonaluno.isSelected()){
        tipo = "Aluno";               }
                else if (jRadioButtonfuncbenefi.isSelected()) {
                 tipo = "Funcionário do benefício";      
                        }
 else if (jRadioButtonProf.isSelected()) {
                 tipo = "Professor";      
                        }
        if (nome.equals("user") && senha.equals("12345") && (tipo.equals("Aluno"))){
            jLabelResposta.setText("Bem-Vindo");
            new JFrameTelaAluno().setVisible(true);
        }if (nome.equals("user") && senha.equals("12345") && (tipo.equals("Funcionário do benefício"))){
            jLabelResposta.setText("Bem-Vindo");
            new JFrameTelaFuncbenefi().setVisible(true);
        }
        else if(nome.equals("user") && senha.equals("12345") && (tipo.equals("Professor"))){
           jLabelResposta.setText("Bem-Vindo");
            new JFrameTelaProf().setVisible(true);
        }
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldnome.setText(null);
        jPasswordFieldsenha.setText(null);
      
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new JFrameCadAluno().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonfuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfuncioActionPerformed
        new JFrameCadFuncio().setVisible(true);
    }//GEN-LAST:event_jButtonfuncioActionPerformed

    private void jButtonProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProfActionPerformed
        new JFrameCadProf().setVisible(true);
    }//GEN-LAST:event_jButtonProfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupfuncao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonProf;
    private javax.swing.JButton jButtonfuncio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelResposta;
    private javax.swing.JLabel jLabelnome;
    private javax.swing.JLabel jLabelsenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldsenha;
    private javax.swing.JRadioButton jRadioButtonProf;
    private javax.swing.JRadioButton jRadioButtonaluno;
    private javax.swing.JRadioButton jRadioButtonfuncbenefi;
    private javax.swing.JTextField jTextFieldnome;
    // End of variables declaration//GEN-END:variables
}
